AWSTemplateFormatVersion: 2010-09-09
Desciption: >-
  zendesk-ticket-generator

Transform:
- AWS::Serverless-2016-10-31

Resources:  
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that creates a bulk of fake Zendesk tickets fairly quickly for demos or testing
      Runtime: nodejs10.x
      Handler: src/ticketCreator/ticketCreator.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      MemorySize: 128
      Timeout: 100
